// Code generated by protoc-gen-go.
// source: paste/entities.proto
// DO NOT EDIT!

/*
Package paste is a generated protocol buffer package.

It is generated from these files:
	paste/entities.proto

It has these top-level messages:
	Paste
	User
*/
package paste

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Paste struct {
	ID      string `protobuf:"bytes,1,opt" json:"ID,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,proto3" json:"Content,omitempty"`
	// paste creation time in UNIX nanoseconds
	CreatedAt int64 `protobuf:"varint,3,opt" json:"CreatedAt,omitempty"`
	// expiration time (if > 0) in nanoseconds, counting from CreatedAt
	ExpireIn int64 `protobuf:"varint,4,opt" json:"ExpireIn,omitempty"`
	// if provided, paste is protected by password
	Password string `protobuf:"bytes,5,opt" json:"Password,omitempty"`
	// if profided, links to Paste that was used to create this one
	ParentID string `protobuf:"bytes,6,opt" json:"ParentID,omitempty"`
}

func (m *Paste) Reset()         { *m = Paste{} }
func (m *Paste) String() string { return proto.CompactTextString(m) }
func (*Paste) ProtoMessage()    {}

type User struct {
	ID    string `protobuf:"bytes,1,opt" json:"ID,omitempty"`
	Name  string `protobuf:"bytes,2,opt" json:"Name,omitempty"`
	Email string `protobuf:"bytes,3,opt" json:"Email,omitempty"`
	// URL to user picture (avatar)
	Picture   string `protobuf:"bytes,4,opt" json:"Picture,omitempty"`
	CreatedAt int64  `protobuf:"varint,5,opt" json:"CreatedAt,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func init() {
}
